version: '3.7'

services:
  db:
    image: postgres:10
    container_name: postgres-10
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./tmp/data/postgresql:/var/lib/postgresql/data
